#include <string.h>
#include <stdlib.h>
#include "library.h"
#include "linked_list.h"
#include <stdio.h>
int main() {
    struct song_node * x = make_list(x, "Dancing in the Dark", "Bruce Springsteen");
    x = insert(x, "Hungry Heart", "Bruce Springsteen");
    x = insert(x, "Piano Man", "Billy Joel");
    x = insert(x, "We Didn't Start the Fire", "Billy Joel");
    x = insert(x, "Don't Stop Believing", "Journey");
    x = insert(x, "Faithfully", "Journey");
    x = insert(x, "Born to Run", "Bruce Springsteen");
    x = insert(x, "Paint it black", "The Rolling Stones");
    x = insert(x, "Satisfaction", "The Rolling Stones");
    x = insert(x, "Slip Slidin' Away", "Paul Simon");
    x = insert(x, "The Wind", "Cat Stevens");
    x = insert(x, "Raised on the Radio", "The Ravyns");
    printf("LINKED LIST TESTS\n====================================\n\nTesting print_list:\n\t");
    print_list(x);
    printf("\n\nTesting find_node:\n\t");
    struct song_node * y = find_node(x, "Faithfully", "Journey");
    printf("{%s, %s}\n\t", y->name, y->artist);
    y = find_node(x, "Piano Man", "Billy Joel");
    printf("{%s, %s}\n\t", y->name, y->artist);
    y = find_node(x, "Satisfaction", "The Rolling Stones");
    printf("{%s, %s}\n\t", y->name, y->artist);
    y = find_node(x, "asdf", "jkl;");
    printf("\n\nTesting find_artist:\n");
    printf("looking for [Bruce Springsteen]\n\t");
    printf("artist found! ");
    y = find_artist(x, "Bruce Springsteen");
    printf("[ ");
    while (y != NULL && strcasecmp(y->artist, "Bruce Springsteen") == 0) {
        printf("{%s, %s} | ", y->name, y->artist);
        y = y->next;
    }
    printf("]\n");
    printf("Looking for [Billy Joel]\n\t");
    printf("artist found! ");
    y = find_artist(x, "Billy Joel");
    printf("[ ");
    while (y != NULL && strcasecmp(y->artist, "Billy Joel") == 0) {
        printf("{%s, %s} | ", y->name, y->artist);
        y = y->next;
    }
    printf("]\n");
    printf("\nTesting random:\n");
    y = find_random(x);
    printf("{%s, %s}\n", y->name, y->artist);
    y = find_random(x);
    printf("{%s, %s}\n", y->name, y->artist);
    y = find_random(x);
    printf("{%s, %s}\n", y->name, y->artist);
    y = find_random(x);
    printf("{%s, %s}\n", y->name, y->artist);
    printf("Testing remove and length:\n");
    printf("Length: %d\n", length(x));
    printf("removing [Piano Man: Billy Joel]\n\t");
    x = remove_node(x, "Piano Man", "Billy Joel");
    print_list(x);
    printf("Length: %d\n", length(x));
    printf("removing [Dancing in the Dark: Bruce Springsteen]\n\t");
    x = remove_node(x, "Dancing in the Dark", "Bruce Springsteen");
    print_list(x);
    printf("Length: %d\n", length(x));
    printf("removing [Satisfaction: The Rolling Stones]\n\t");
    x = remove_node(x, "Satisfaction", "The Rolling Stones");
    print_list(x);
    printf("Length: %d\n", length(x));
    printf("Testing free_list:\n");
    x = free_list(x);
    printf("list after free_list:\n");
    print_list(x);
    struct song_node **lib = make_lib();
    new_song(lib, "Hungry Heart", "Bruce Springsteen");
    new_song(lib, "Piano Man", "Billy Joel");
    new_song(lib, "We Didn't Start the Fire", "Billy Joel");
    new_song(lib, "Don't Stop Believing", "Journey");
    new_song(lib, "Faithfully", "Journey");
    new_song(lib, "Born to Run", "Bruce Springsteen");
    new_song(lib, "Paint it black", "The Rolling Stones");
    new_song(lib, "Satisfaction", "The Rolling Stones");
    new_song(lib, "Slip Slidin' Away", "Paul Simon");
    new_song(lib, "The Wind", "Cat Stevens");
    new_song(lib, "Raised on the Radio", "The Ravyns");
    printf("MUSIC LIBRARY TESTS\n====================================\n\n");
    printf("Testing print letter\n");
    print_lib_letter(lib, 'b');
    printf("\nTesting print_lib\n");
    print_lib(lib);
    printf("\nTesting find artist:\n");
    print_lib_artist(lib, "Bruce Springsteen");
    print_lib_artist(lib, "Billy Joel");
    print_lib_artist(lib, "Paul Simon");
    printf("\n\nTesting remove_song:\nremoving [Faithfully, Journey]\n");
    remove_song(lib, "Faithfully", "Journey");
    print_lib(lib);
    printf("\nTesting free_lib\n");
    free_lib(lib);
    print_lib(lib);
    printf("\nAdding songsto empty lib:\n");
    new_song(lib, "Hungry Heart", "Bruce Springsteen");
    new_song(lib, "Piano Man", "Billy Joel");
    new_song(lib, "We Didn't Start the Fire", "Billy Joel");
    new_song(lib, "Don't Stop Believing", "Journey");
    new_song(lib, "Faithfully", "Journey");
    new_song(lib, "Born to Run", "Bruce Springsteen");
    new_song(lib, "Paint it black", "The Rolling Stones");
    new_song(lib, "Satisfaction", "The Rolling Stones");
    new_song(lib, "Slip Slidin' Away", "Paul Simon");
    new_song(lib, "The Wind", "Cat Stevens");
    new_song(lib, "Raised on the Radio", "The Ravyns");
    print_lib(lib);
    free_lib(lib);

//    struct song_node ** lib = make_lib();
//    new_song(lib, "Dancing in the Dark", "Bruce Springsteen");
//    new_song(lib, "Hungry Heart", "Bruce Springsteen");
//    new_song(lib, "Piano Man", "Billy Joel");
//    new_song(lib, "We Didn't Start the Fire", "Billy Joel");
//   new_song(lib, "Don't Stop Believing", "Journey");
//    print_lib(lib);
//    print_lib_letter(lib, 'd');
//    print_lib_artist(lib, "Bruce Springsteen");
//    struct song_node *x = malloc(sizeof(struct song_node));
//    strcpy(x->name, "The Phoenix");
//    strcpy(x->artist, "Fall Out Boy");
//    x = insert(x, "Dancing in the Dark", "Bruce Springsteen");
//    x = insert(x, "Hungry Heart", "Bruce Springsteen");
//    x = insert(x, "Piano Man", "Billy Joel");
//    x = insert(x, "We Didn't Start the Fire", "Billy Joel");
//    x = insert(x, "Don't Stop Believing", "Journey");
//    struct song_node * y = find_random(x);
//    x = remove_node(x, "piano man", "billy joel");
//    x = remove_node(x, "Hungry heArt", "Bruce Springsteen");
//    x = remove_node(x, "Don't Stop believing", "Journey");
//    printf("y points to %s by %s\n", y->name, y->artist);
//    print_list(x);
//    free_list(x);
    return 0;
}
